# Generated by Django 3.2 on 2021-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SavBlock', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.CharField(choices=[(0, 'Supporter (non-member)'), (1, 'Anak'), (2, 'Uso'), (3, 'Chief')], default=0, max_length=50),
        ),
    ]
