# Generated by Django 3.1.5 on 2021-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SavBlock', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ranking',
            field=models.CharField(choices=[('Supporter', 'Supporter (non-member)'), ('Anak', 'Anak'), ('Uso', 'Uso'), ('Chief', 'Chief')], default='Supporter', max_length=50),
        ),
    ]
