# Generated by Django 3.2 on 2021-05-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SavBlock', '0009_auto_20210425_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tribe',
            field=models.CharField(choices=[('NaKoaHema', 'Na Koa Hema'), ('Alakai', "Alaka'i")], default=None, max_length=50),
        ),
    ]
